server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/mydb
    username: root
    password: secret
  jpa:
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
          batch_versioned_data: true
    hibernate:
      ddl-auto: none

# Graphql
graphql:
  servlet:
    mapping: /apis/graphql